version: 2.1

orbs:
  virtuaexecutors: virtuaorbs/executors@0.1.0
  virtuacommands: virtuaorbs/commands@0.5.0

jobs:
  test-creation-job:
    executor: virtuaexecutors/mongoruby_2-6-3
    steps:
      - virtuacommands/run-rspec-tests:
          suite: 'spec/controllers/invitations_spec.rb[1:1]'
  test-list-job:
    executor: virtuaexecutors/mongoruby_2-6-3
    steps:
      - virtuacommands/run-rspec-tests:
          suite: 'spec/controllers/invitations_spec.rb[1:2]'
  test-update-job:
    executor: virtuaexecutors/mongoruby_2-6-3
    steps:
      - virtuacommands/run-rspec-tests:
          suite: 'spec/controllers/invitations_spec.rb[1:3]'
  test-deletion-job:
    executor: virtuaexecutors/mongoruby_2-6-3
    steps:
      - virtuacommands/run-rspec-tests:
          suite: 'spec/controllers/invitations_spec.rb[1:4]'
  rubocop-job:
    executor: virtuaexecutors/mongoruby_2-6-3
    steps:
      - perform-rubocop-analysis:
          directories: "controllers/"
  doc-job:
    executor: virtuaexecutors/mongoruby_2-6-3
    steps:
      - virtuacommands/generate-documentation
  deploy-job:
    executor: virtuaexecutors/mongoruby_2-6-3
    steps:
      - virtuacommands/perform-capistrano-command:
          command: "deploy"
  restart-job:
    executor: virtuaexecutors/mongoruby_2-6-3
    steps:
      - virtuacommands/perform-capistrano-command:
          command: "deploy:start"

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - rubocop-job
      - test-creation-job:
          requires:
            - rubocop-job
      - test-list-job:
          requires:
            - rubocop-job
      - test-update-job:
          requires:
            - rubocop-job
      - test-deletion-job:
          requires:
            - rubocop-job
      - doc-job
      - deploy-job:
          requires:
            - test-creation-job
            - test-list-job
            - test-update-job
            - test-deletion-job
          filters:
            branches:
              only: master
  daily-restart:
    triggers:
      - schedule:
          cron: "5 4 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - restart-job