version: 2.1

orbs:
  virtuaexecutors: virtuaorbs/executors@0.1.0
  virtuacommands: virtuaorbs/commands@0.4.1

jobs:
  test-creation-job:
    executor: virtuaexecutors/mongoruby_2-6-3
    steps:
      - virtuacommands/run-test-suites:
          filename: 'tests'
          suite: 'spec/controllers/invitations_spec.rb[1:1]'
          formatter: RspecJunitFormatter
          extension: xml
  test-list-job:
    executor: virtuaexecutors/mongoruby_2-6-3
    steps:
      - virtuacommands/run-test-suites:
          filename: 'tests'
          suite: 'spec/controllers/invitations_spec.rb[1:2]'
          formatter: RspecJunitFormatter
          extension: xml
  test-update-job:
    executor: virtuaexecutors/mongoruby_2-6-3
    steps:
      - virtuacommands/run-test-suites:
          filename: 'tests'
          suite: 'spec/controllers/invitations_spec.rb[1:3]'
          formatter: RspecJunitFormatter
          extension: xml
  test-deletion-job:
    executor: virtuaexecutors/mongoruby_2-6-3
    steps:
      - virtuacommands/run-test-suites:
          filename: 'tests'
          suite: 'spec/controllers/invitations_spec.rb[1:4]'
          formatter: RspecJunitFormatter
          extension: xml
  doc-job:
    executor: virtuaexecutors/mongoruby_2-6-3
    steps:
      - virtuacommands/generate-documentation
  deploy-job:
    executor: virtuaexecutors/mongoruby_2-6-3
    steps:
      - virtuacommands/perform-capistrano-command:
          command: "deploy"
  restart-job:
    executor: virtuaexecutors/mongoruby_2-6-3
    steps:
      - virtuacommands/perform-capistrano-command:
          command: "deploy:start"

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - test-creation-job
      - test-list-job
      - test-update-job
      - test-deletion-job
      - doc-job
      - deploy-job:
          requires:
            - test-creation-job
            - test-list-job
            - test-update-job
            - test-deletion-job
          filters:
            branches:
              only: master
  daily-restart:
    triggers:
      - schedule:
          cron: "5 6 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - restart-job