errors:
  common:
    app_key:
      forbidden: 'https://github.com/jdr-tools/wiki/wiki/Common-errors#application-not-premium'
      required: 'https://github.com/jdr-tools/wiki/wiki/Common-errors#application-key-not-given'
      unknown: 'https://github.com/jdr-tools/wiki/wiki/Common-errors#application-key-not-found'
    token:
      required: 'https://github.com/jdr-tools/wiki/wiki/Common-errors#gateway-token-not-given'
      unknown: 'https://github.com/jdr-tools/wiki/wiki/Common-errors#gateway-token-not-found'
  creation:
    campaign_id:
      required: 'https://github.com/jdr-tools/wiki/wiki/Invitations-API#campaign-id-not-given'
      unknown: 'https://github.com/jdr-tools/wiki/wiki/Invitations-API#campaign-not-found'
    session_id:
      forbidden: 'https://github.com/jdr-tools/wiki/wiki/Invitations-API#not-authorized-creation'
      required: 'https://github.com/jdr-tools/wiki/wiki/Invitations-API#session-id-not-given'
      unknwon: 'https://github.com/jdr-tools/wiki/wiki/Invitations-API#session-not-found'
    username:
      already_accepted: 'https://github.com/jdr-tools/wiki/wiki/Invitations-API#invitation-already-accepted'
      already_pending: 'https://github.com/jdr-tools/wiki/wiki/Invitations-API#invitation-already-pending'
      required: 'https://github.com/jdr-tools/wiki/wiki/Invitations-API#username-not-given'
      unknown: 'https://github.com/jdr-tools/wiki/wiki/Invitations-API#username-not-found'
  deletion:
    invitation_id:
      unknown: 'https://github.com/jdr-tools/wiki/wiki/Invitations-API#invitation-not-found'
    session_id:
      forbidden: 'https://github.com/jdr-tools/wiki/wiki/Invitations-API#not-authorized-update'
      required: 'https://github.com/jdr-tools/wiki/wiki/Invitations-API#session-id-not-given-1'
      unknwon: 'https://github.com/jdr-tools/wiki/wiki/Invitations-API#session-not-found-1'
  own_invitations:
    session_id:
      required: ''
      unknown: ''
  update:
    invitation_id:
      unknown: 'https://github.com/jdr-tools/wiki/wiki/Invitations-API#invitation-not-found'
    session_id:
      forbidden: 'https://github.com/jdr-tools/wiki/wiki/Invitations-API#not-authorized-update'
      required: 'https://github.com/jdr-tools/wiki/wiki/Invitations-API#session-id-not-given-1'
      unknwon: 'https://github.com/jdr-tools/wiki/wiki/Invitations-API#session-not-found-1'
